"""
Land Governance Platform SDK - Simulation Data Models
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class SimulationParams(BaseModel):
    policy_variable: str = Field(default="digital_cadastre", description="Target policy intervention (e.g. land_ceiling, digital_cadastre, zoning_density, tax_incentive, fast_track_courts)")
    target_value: float = Field(default=85.0, description="Target value for policy variable")
    unit: str = Field(default="%", description="Measurement unit (e.g. %, acres, ratio, courts)")
    investment_cr: float = Field(default=100.0, description="Fiscal allocation in Crores INR")
    state: str = Field(default="National", description="Target administrative jurisdiction")

class SimulationSummary(BaseModel):
    digitization_gain_pct: float = Field(description="Projected increase in digital cadastre coverage")
    dispute_reduction_pct: float = Field(description="Projected reduction in land boundary litigation")
    urbanization_rate_pct: float = Field(description="Projected annual urban land conversion rate")
    climate_resilience_score: float = Field(description="Index score for drought & flood exposure mitigation")
    projected_litigation_savings_cr: float = Field(description="Estimated fiscal savings in litigation costs (Cr INR)")
    confidence_score_pct: float = Field(default=92.4, description="Overall model goodness-of-fit score (%)")
    confidence_metric: str = Field(default="dispute_reduction_pct", description="Target metric bracketed by confidence_range ('dispute_reduction_pct')")
    confidence_range: List[float] = Field(default_factory=lambda: [19.8, 26.2], description="Ensemble dispersion interval [lower, upper] directly bracketing dispute_reduction_pct")

class SimulationResult(BaseModel):
    source: str = Field(default="live", description="Data origin ('live' or 'offline')")
    is_offline: bool = Field(default=False, description="True if generated by offline fallback engine")
    model_version: str = Field(default="v1.2_hybrid_rf_linear", description="ML model identifier (e.g. 'v1.2_hybrid_rf_linear' or 'offline_approx_v1')")
    parameters: SimulationParams
    summary: SimulationSummary
    explainability: Dict[str, Any] = Field(default_factory=dict, description="Top feature weights and decision tree attribution")
    trajectory: List[Dict[str, Any]] = Field(default_factory=list, description="7-year temporal projection trajectory (2024-2030)")
    recommendations: List[str] = Field(default_factory=list, description="Policy execution directives")

    def to_dataframe(self) -> Any:
        """Converts the temporal trajectory projection into a Pandas DataFrame with metadata source tags."""
        try:
            import pandas as pd
            df = pd.DataFrame(self.trajectory)
            df["source"] = self.source
            df.attrs["source"] = self.source
            df.attrs["is_offline"] = self.is_offline
            df.attrs["model_version"] = self.model_version
            return df
        except ImportError:
            raise ImportError("Pandas is required for .to_dataframe(). Install via 'pip install land-governance-sdk[pandas]'")

class SimulationComparison(BaseModel):
    scenario_a: SimulationResult
    scenario_b: SimulationResult
    deltas: Dict[str, float] = Field(description="Difference metrics (Scenario B minus Scenario A)")
    winner: str = Field(description="Recommended policy scenario based on net impact")
