"""create_innovation_portal_tables

Revision ID: 03d0c1bde721
Revises: 3188fee5134f
Create Date: 2026-09-29 01:07:45.698384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '03d0c1bde721'
down_revision: Union[str, Sequence[str], None] = '3188fee5134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenge_type', sa.Enum('HACKATHON', 'GRANT', 'RESEARCH_CALL', 'PILOT_PROJECT', name='challengetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'COMPLETED', name='challengestatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eligibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prize_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('deadline', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('proposal_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_challenge_type'), 'challenges', ['challenge_type'], unique=False)
    op.create_index(op.f('ix_challenges_created_by'), 'challenges', ['created_by'], unique=False)
    op.create_index(op.f('ix_challenges_organization'), 'challenges', ['organization'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=False)
    op.create_table('proposal_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'user_id', name='uq_proposal_user_vote')
    )
    op.create_index(op.f('ix_proposal_votes_proposal_id'), 'proposal_votes', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_proposal_votes_user_id'), 'proposal_votes', ['user_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detailed_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'FUNDED', 'COMPLETED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('funding_status', sa.Enum('NOT_APPLICABLE', 'PENDING', 'PARTIALLY_DISBURSED', 'DISBURSED', name='fundingstatus'), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_challenge_id'), 'proposals', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_proposals_funding_status'), 'proposals', ['funding_status'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_index(op.f('ix_proposals_submitted_by'), 'proposals', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_proposals_title'), 'proposals', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_title'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_submitted_by'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_funding_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_challenge_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_proposal_votes_user_id'), table_name='proposal_votes')
    op.drop_index(op.f('ix_proposal_votes_proposal_id'), table_name='proposal_votes')
    op.drop_table('proposal_votes')
    op.drop_index(op.f('ix_challenges_title'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_organization'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_created_by'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_challenge_type'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
